FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY apps/api/go.mod apps/api/go.sum ./
RUN go mod download

COPY apps/api ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /out/tiss-api ./cmd/api

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /out/tiss-api /app/tiss-api
EXPOSE 8080
ENTRYPOINT ["/app/tiss-api"]
